logging:
    # pattern:
    #     console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %highlight(%-5level) | %logger{36} | %msg%n"
    level:
        root: INFO
        org:
            springframework: WARN
        com:
            ulisesbocchio:
                jasyptspringboot: WARN
            nk: DEBUG